name: github pages

on:
    push:
        branches:
            - main # Set a branch name to trigger deployment

jobs:
    deploy:
        runs-on: ubuntu-18.04
        env:
            MY_SECRET: ${{ secrets.admin_access }}
            MY_MAIL: oldsince2017@gmail.com
            MY_NAME: kk
            GITHUB_REPOSITORY: timebox-tool/dist.git
            DIST_DIR: ./build
        steps:
            - uses: actions/checkout@v2

            - name: Set node environment
              uses: actions/setup-node@v1
              with:
                  node-version: "14"

            - name: Build
              run: |
                  yarn
                  yarn build

            - name: Push build result to remote
              run: |
                  cd $DIST_DIR

                  git init
                  git status


                  git config --global user.email $MY_MAIL
                  git config --global user.name $MY_NAME
                  git remote add origin https://$MY_SECRET@github.com/$GITHUB_REPOSITORY.git

                  git add --all
                  git checkout -b gh-pages
                  git commit -m "deploy to github pages"
                  git push origin gh-pages -f
                  echo 🤘🤘🤘 go to check your app ~
